---
# tasks file for mysql

- name: Merge the ports lists
  set_fact:  port_name="{{ item }}"
  with_sequence: start={{ alisql_ins.split('-')[0] }} end={{ alisql_ins.split('-')[-1] }}
  register: port_result

- name: construct the test port
  set_fact:
    test_port: "{{ port_result.results | map(attribute='ansible_facts.port_name') | list | join(', ') }}"

- name: use the sysbench to test the database 
  shell: |

    sysbench  /usr/local/share/sysbench/tests/include/oltp_legacy/oltp.lua \
    --oltp-table-size={{ sysbench_table_size }} \
    --oltp-tables-count={{ sysbench_table_count }} \
    --mysql-db=sysbench \
    --report-interval=1 \
    --max-requests=0 \
    --time={{ test_time }} \
    --mysql-host={{ mysql_host }} \
    --mysql-port="{{ test_port }}" \
    --mysql-password=123456 \
    --mysql-user=root \
    --mysql-table-engine=innodb \
    --threads={{ item }}  run
  with_items:
    - 200
    - 400
    - 800
  register: alisql_result

- debug: var=alisql_result 

- name: Kill alisql server on ARM64 Server
  shell: ps -ef | grep mysql | grep -v grep | awk '{print "kill -9 " $2}' | sh & 
